name: learn-github-actions
on: [ push ]
jobs:
  setup-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: [ '3.6', '3.7', '3.8', '3.9' ]
      - run: python --version
      - run: python actions-demo/demo.py
