name: testing-with-coverage
on: [ push ]
jobs:
  test-with-coverage:
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9']
    runs-on: ubuntu-latest
    steps:
      - name: Fetch repository
        uses: actions/checkout@v3
      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Generate Coverage Report
        run: |
          pip install coverage
          coverage run --source=actions-demo actions-demo/TestDemo.py
          coverage report